site_name: Terraform for さくらのクラウド
site_url: https://sacloud.github.io/terraform-provider-sakuracloud
site_description: Terrform for さくらのクラウド
site_author: '@yamamoto-febc'
copyright: Copyright (C) 2017 Kazumichi Yamamoto.
google_analytics: ['UA-63739336-5','auto']
theme: readthedocs
extra_css:
  - css/extra.css
pages:
  - ホーム: index.md
  - ドキュメント:
    - インストールガイド: installation.md
    - ブログ/記事/読み物: articles.md
  - 設定リファレンス:
    - 全体/共通項目:
      - プロバイダ: configuration/provider.md
    - リソース:
      - サーバ: configuration/resources/server.md
      - ディスク: configuration/resources/disk.md
      - アーカイブ: configuration/resources/archive.md
      - ISOイメージ(CD-ROM): configuration/resources/cdrom.md
      - スイッチ: configuration/resources/switch.md
      - ルータ: configuration/resources/internet.md
      - サブネット: configuration/resources/subnet.md
      - パケットフィルタ: configuration/resources/packet_filter.md
      - パケットフィルタ(ルール): configuration/resources/packet_filter_rule.md
      - ブリッジ: configuration/resources/bridge.md
      - ロードバランサ: configuration/resources/load_balancer.md
      - VPCルータ: configuration/resources/vpc_router.md
      - データベース: configuration/resources/database.md
      - NFS: configuration/resources/nfs.md
      - スタートアップスクリプト: configuration/resources/note.md
      - 公開鍵: configuration/resources/ssh_key.md
      - 公開鍵(生成): configuration/resources/ssh_key_gen.md
      - アイコン: configuration/resources/icon.md
      - DNS: configuration/resources/dns.md
      - GSLB: configuration/resources/gslb.md
      - シンプル監視: configuration/resources/simple_monitor.md
      - 自動バックアップ: configuration/resources/auto_backup.md
      - オブジェクトストレージ: configuration/resources/bucket_object.md
    - 特殊なリソース:
      - サーバ コネクタ: configuration/resources/server_connector.md
    - データソース:
      - データソース: configuration/resources/data_resource.md
