name: Release
on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'
env:
  GOPROXY: https://proxy.golang.org
  TERRAFORM_VERSION: 0.12.20
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Set up Go environemnt variables
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup tools
        run: make tools

      - name: make build-x
        run: make build-x

      - name: make release
        run: make release
