name: Tests
on: [push, pull_request]
env:
  GOPROXY: https://proxy.golang.org
jobs:
  lint-text:
    name: lint-text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: lint a document with textlint
        uses: sacloud/textlint-action@v0.0.3
        # with:
        #   working-directory: .
  lint-go:
    name: lint-go
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup tools
        run: | 
          make tools

      - name: make lint-go
        run:  |
          make lint-go

  licenses-check:
    name: licenses-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup tools
        run: make tools

      - name: make go-licenses-check
        run: make go-licenses-check
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-22.04, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup tools
        run: | 
          make tools

      - name: make test
        run: |
          make test
