name: Tests
on: [push, pull_request]
env:
  GOPROXY: https://proxy.golang.org
jobs:
  lint-text:
    name: lint-text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: |
          make tools

      - name: make lint-text
        run:  |
          make lint-text
  lint-go:
    name: lint-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: | 
          make tools

      - name: make lint-go
        run:  |
          # Explicitly set GOROOT to avoid golangci-lint/issues/3107
          GOROOT=$(go env GOROOT)
          export GOROOT
          make lint-go

  licenses-check:
    name: licenses-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: make tools

      - name: make go-licenses-check
        run: make go-licenses-check
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: | 
          make tools

      - name: make test
        run: |
          make test
